version: '3.7'

networks:
    constrsw:

volumes:
    # No terminal, criar o volume externo: docker volume create constrsw-keycloak-data
    constrsw-keycloak-data:
        external: true
        
services:

  keycloak:
    container_name: keycloak
    build:
      context: backend/utils/keycloak
      dockerfile: Dockerfile
    image: constrsw/keycloak
    environment:
      - KC_HEALTH_ENABLED=${KC_HEALTH_ENABLED}
      - KC_METRICS_ENABLED=${KC_METRICS_ENABLED}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - constrsw-keycloak-data:/opt/keycloak/data
      - ./backend/utils/keycloak:/opt/keycloak/data/import     
    networks:
      - constrsw
    ports:
      - ${KEYCLOAK_EXTERNAL_CONSOLE_PORT}:${KEYCLOAK_INTERNAL_CONSOLE_PORT}
    command: start-dev --import-realm
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f ${KEYCLOAK_INTERNAL_HOST}:${KEYCLOAK_INTERNAL_API_PORT}/health" ]
      start_period: 300s
      interval: 10s
      timeout: 10s
      retries: 50
 
  fastapi:
    container_name: fastapi
    build:
      context: backend/oauth
    image: fastapi-api
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - REALM_NAME=${REALM_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    networks:
      - constrsw
    ports:
      - "8000:8000"
    depends_on:
      - keycloak