networks:
    constrsw:

volumes:
    # No terminal, criar o volume externo: docker volume create constrsw-keycloak-data
    constrsw-keycloak-data:
        external: true
    # No terminal, criar o volume externo: docker volume create constrsw-postgresql-data
    constrsw-postgresql-data:
        external: true
    # No terminal, criar os volumes externos: docker volume create constrsw-sonarqube-data && docker volume create constrsw-sonarqube-extensions && docker volume create constrsw-sonarqube-logs
    constrsw-sonarqube-data:
        external: true
    constrsw-sonarqube-extensions:
        external: true
    constrsw-sonarqube-logs:
        external: true
        
services:

  keycloak:
    container_name: keycloak
    build:
      context: backend/utils/keycloak
      dockerfile: Dockerfile
    image: constrsw/keycloak
    environment:
      - KC_HEALTH_ENABLED=${KC_HEALTH_ENABLED}
      - KC_METRICS_ENABLED=${KC_METRICS_ENABLED}
      - KC_HTTP_MANAGEMENT_PORT=${KC_HTTP_MANAGEMENT_PORT}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - constrsw-keycloak-data:/opt/keycloak/data
      - ./backend/utils/keycloak:/opt/keycloak/data/import     
    networks:
      - constrsw
    ports:
      - ${KEYCLOAK_EXTERNAL_CONSOLE_PORT}:${KEYCLOAK_INTERNAL_CONSOLE_PORT}
      - ${KEYCLOAK_EXTERNAL_METRICS_PORT}:${KEYCLOAK_INTERNAL_METRICS_PORT}
    command: start-dev --import-realm
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f ${KEYCLOAK_INTERNAL_HOST}:${KEYCLOAK_INTERNAL_METRICS_PORT}/health" ]
      start_period: 50s
      interval: 10s
      timeout: 10s
      retries: 10

  # PostgreSQL
  postgresql:
    container_name: postgresql
    build:
      context: ./backend/utils/postgresql/
      dockerfile: Dockerfile
      args:
        POSTGRESQL_HOST_AUTH_METHOD: ${POSTGRESQL_HOST_AUTH_METHOD}
        POSTGRESQL_DATA: ${POSTGRESQL_DATA}
        POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
        POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    image: constrsw/postgresql
    environment:
      - POSTGRESQL_INTERNAL_HOST=${POSTGRESQL_INTERNAL_HOST}
      - POSTGRESQL_INTERNAL_PORT=${POSTGRESQL_INTERNAL_PORT}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
    volumes:
      # No terminal, criar o volume externo: docker volume create constrsw-postgresql-data
      - constrsw-postgresql-data:${POSTGRESQL_DATA}
    networks:
      - constrsw
    ports:
      - ${POSTGRESQL_EXTERNAL_PORT}:${POSTGRESQL_INTERNAL_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME}" ]
      start_period: 20s
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    
   # SonarQube
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    environment:
      - SONAR_WEB_HOST=${SONAR_WEB_HOST}
      - SONAR_WEB_PORT=${SONAR_WEB_PORT}
      - SONAR_WEB_CONTEXT=${SONAR_WEB_CONTEXT}
      - SONAR_JDBC_URL=jdbc:postgresql://${POSTGRESQL_INTERNAL_HOST}:${POSTGRESQL_INTERNAL_PORT}/sonar
      - SONAR_JDBC_USERNAME=${POSTGRESQL_USERNAME}
      - SONAR_JDBC_PASSWORD=${POSTGRESQL_PASSWORD}
      - SONARQUBE_USER=${SONARQUBE_USER}
      - SONARQUBE_PASSWORD=${SONARQUBE_PASSWORD}
    volumes:
      # No terminal, criar o volume externo: docker volume create constrsw-sonarqube-data
      - constrsw-sonarqube-data:/opt/sonarqube/data
      - constrsw-sonarqube-extensions:/opt/sonarqube/extensions
      - constrsw-sonarqube-logs:/opt/sonarqube/logs
    networks:
      - constrsw
    ports:
      - "9000:9000"
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f ${SONARQUBE_INTERNAL_PROTOCOL}://${SONARQUBE_INTERNAL_HOST}:${SONARQUBE_INTERNAL_PORT}/api/system/status || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 10
    restart: always

  oauth-api:
    container_name: oauth-api
    build:
      context: ./backend/oauth # Diretório que contém o Dockerfile da API
      dockerfile: Dockerfile
    image: constrsw/oauth-api
    command: uvicorn oauth_api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000" # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    networks:
      - constrsw
    volumes:
      # Monta o código-fonte da API dentro do contêiner para que o --reload funcione
      - ./backend/oauth:/app 
    depends_on:
      keycloak:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    restart: always
    # Garanta que você tenha um arquivo .env na pasta backend/oauth
    env_file:
      - ./backend/oauth/.env 

  # Frontend React
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: constrsw/frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
      - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
    networks:
      - constrsw
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
    depends_on:
      keycloak:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
