name: SonarQube Analysis

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Adicionado passo para baixar dependências explicitamente
      - name: Install Dependencies
        working-directory: ./backend/oauth
        run: go mod download

      - name: Run Tests and Generate Coverage
        working-directory: ./backend/oauth/tests
        # CORREÇÃO: Variáveis de ambiente agora correspondem ao config.go
        env:
          OAUTH_PORT: 8181
          KEYCLOAK_INTERNAL_HOST: "localhost"
          KEYCLOAK_INTERNAL_API_PORT: 8080
          KEYCLOAK_REALM: "constrsw"
          KEYCLOAK_CLIENT_ID: "oauth"
          KEYCLOAK_CLIENT_SECRET: "a-secret-for-ci"
        run: go test ./... -coverprofile=coverage.out -json > test-report.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: ./backend/oauth
